CREATE TABLE VEICULOS 
( 
placa CHAR(8), 
ano 
NUMBER(4), 
km 
NUMBER(6), 
marca VARCHAR(50), 
modelo VARCHAR(50) -- repare que não há virgula aqui 
);

INSERT INTO VEICULOS 
VALUES ('IJK-1212', 2022, 0, 'Chevrolet', 'Onix');

INSERT INTO VEICULOS (placa, ano, km, marca, modelo) 
VALUES ('IJM-1556', 2015, 72045, 'Volkswagen', 'Gol');

SELECT * FROM VEICULOS;

SELECT PLACA, ANO FROM VEICULOS WHERE KM = 0;

SELECT PLACA, ANO, KM FROM VEICULOS WHERE KM = 0;

SELECT PLACA, ANO, MODELO FROM VEICULOS WHERE ANO <= 2022;

SELECT PLACA, ANO, MODELO FROM VEICULOS WHERE ANO < 2022;

UPDATE VEICULO SET MODELO = 'Cruze' WHERE PLACA = 'IJK-1212';

SELECT * FROM VEICULOS;

UPDATE VEICULOS SET MODELO = 'Cruze' WHERE PLACA = 'IJK-1212';

SELECT * FROM VEICULOS;

UPDATE VEICULOS SET KM = KM + 100 WHERE ANO BETWEEN 2015 AND 2021;

SELECT * FROM VEICULOS;

UPDATE VEICULOS SET KM = KM + 100 WHERE ANO BETWEEN 2015 AND 2021;

SELECT * FROM VEICULOS;

UPDATE VEICULOS SET KM = KM + 100 WHERE ANO BETWEEN 2015 AND 2021;

SELECT * FROM VEICULOS;

SELECT * FROM VEICULOS;

DELETE FROM VEICULOS WHERE PLACA = 'IJM-1556';

SELECT * FROM VEICULOS;

DELETE FROM VEICULOS WHERE MARCA = 'Chevrolet' AND KM > 500000;

SELECT * FROM VEICULOS;

SELECT PLACA, KM FROM VEICULOS ORDER BY KM;

SELECT PLACA, KM FROM VEICULOS ORDER BY KM, ANO DESC;

SELECT PLACA, KM FROM VEICULOS ORDER BY KM ASC, ANO DESC;

INSERT INTO VEICULOS (placa, ano, km, marca, modelo) 
VALUES ('IJM-1556', 2015, 72045, 'Volkswagen', 'Gol');

SELECT PLACA, KM FROM VEICULOS ORDER BY KM ASC, ANO DESC;

SELECT PLACA, ANO, KM FROM VEICULOS ORDER BY KM ASC, ANO DESC;

SELECT COUNT(*) FROM VEICULOS;

SELECT COUNT(*) FROM VEICULOS WHERE MARCA = 'Ford';

