CREATE TABLE PRODS 
( 
codigo NUMERIC(3) NOT NULL, 
nome VARCHAR(50) NOT NULL, 
preco NUMERIC (5,2) NOT NULL, 
tipo CHAR(1) NULL, -- [S]uprimento, [C]omponente, [P]eriférico 
CONSTRAINT PK1 PRIMARY KEY (codigo) 
);

INSERT INTO PRODS VALUES( 10, 'HD' ,200 ,'C');

INSERT INTO PRODS VALUES( 11, 'Memoria' ,250 ,'C');

INSERT INTO PRODS VALUES( 12, 'Impressora' ,680 ,'P');

INSERT INTO PRODS VALUES( 13, 'Processador' ,600 ,'C');

INSERT INTO PRODS VALUES( 14, 'DVD-RW' ,2 ,'S');

INSERT INTO PRODS VALUES( 15, 'Papel A4' ,19 ,'S');

INSERT INTO PRODS VALUES( 16, 'Scanner' ,199 ,'P');

SELECT COUNT(*) FROM PRODS;

SELECT DISTINCT TIPO FROM PRODS;

SELECT TIPO, COUNT(*) AS TOTAL FROM PRODS GROUP BY TIPO;

SELECT AVG(PRECO) FROM PRODS;

SELECT AVG(PRECO) FROM PRODS WHERE TIPO = 'S';

SELECT TIPO, AVG(PRECO) AS MEDIA FROM PRODS GROUP BY TIPO;

SELECT COUNT(DISTINCT TIPO) FROM PRODS;

SELECT TIPO, COUNT(*) AS TOTAL FROM PRODS GROUP BY TIPO;

SELECT AVG(PRECO) FROM PRODS;

SELECT AVG(PRECO) FROM PRODS WHERE TIPO = 'S';

SELECT TIPO, AVG(PRECO) AS MEDIA FROM PRODS GROUP BY TIPO;

SELECT TIPO, AVG(PRECO) AS MEDIA FROM PRODS GROUP BY TIPO HAVING AVG(PRECO) > 300;

SELECT titulo 
FROM PRODUTOS 
WHERE preco > 
(SELECT preco 
FROM PRODUTOS 
WHERE cod_produto = 9);

